wandb_version: 1

id:
  desc: null
  value: boot_rainbow
seed:
  desc: null
  value: 123
disable_cuda:
  desc: null
  value: false
game:
  desc: null
  value: bank_heist
T_max:
  desc: null
  value: 100000
max_episode_length:
  desc: null
  value: 108000
history_length:
  desc: null
  value: 4
architecture:
  desc: null
  value: canonical
hidden_size:
  desc: null
  value: 512
noisy_std:
  desc: null
  value: 0.5
atoms:
  desc: null
  value: 51
V_min:
  desc: null
  value: -10
V_max:
  desc: null
  value: 10
model:
  desc: null
  value: null
memory_capacity:
  desc: null
  value: 1000000
replay_frequency:
  desc: null
  value: 4
priority_exponent:
  desc: null
  value: 0.5
priority_weight:
  desc: null
  value: 0.4
multi_step:
  desc: null
  value: 3
discount:
  desc: null
  value: 0.99
target_update:
  desc: null
  value: 8000
reward_clip:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 6.25e-05
adam_eps:
  desc: null
  value: 0.00015
batch_size:
  desc: null
  value: 32
learn_start:
  desc: null
  value: 20000
evaluate:
  desc: null
  value: false
evaluation_interval:
  desc: null
  value: 1000
evaluation_episodes:
  desc: null
  value: 10
evaluation_size:
  desc: null
  value: 500
render:
  desc: null
  value: false
enable_cudnn:
  desc: null
  value: false
checkpoint_interval:
  desc: null
  value: 0
memory:
  desc: null
  value: null
disable_bzip_memory:
  desc: null
  value: false
num_ensemble:
  desc: null
  value: 5
beta_mean:
  desc: null
  value: 0.5
temperature:
  desc: null
  value: 40
ucb_infer:
  desc: null
  value: 1
ucb_train:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712657303.496834
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.17
      5: 0.15.10
      8:
      - 3
      - 5
